# Generated by Django 3.2 on 2021-07-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='person',
        ),
        migrations.AddField(
            model_name='car',
            name='person',
            field=models.ManyToManyField(related_name='cars', to='home.Person'),
        ),
    ]
